changes in customer

diff --git a/.github/workflows/Build.yaml b/.github/workflows/Build.yaml
--- a/.github/workflows/Build.yaml
+++ b/.github/workflows/Build.yaml
@@ -125,3 +125,58 @@ jobs:
           # Send message to Teams
           curl -X POST -H 'Content-Type: application/json' \
             -d "{\"text\":\"$MESSAGE\"}" ${{ secrets.TEAMS_WEBHOOK_URL }}
+
+  deploy-to-eks:
+    needs: build-and-push  # Ensure the deploy job runs after the build-and-push job
+
+    runs-on: ubuntu-latest
+
+    steps:
+      # Step 1: Checkout the Helm chart repository
+      - name: Checkout Helm Chart Repo
+        uses: actions/checkout@v4
+        with:
+          repository: Ramesh-Kumhar/DIGIT-DevOps
+          path: helm-charts
+
+      # Step 2: Set up Helm and kubectl
+      - name: Set up Helm and kubectl
+        run: |
+          curl -LO https://get.helm.sh/helm-v3.9.1-linux-amd64.tar.gz
+          tar -zxvf helm-v3.9.1-linux-amd64.tar.gz
+          sudo mv linux-amd64/helm /usr/local/bin/helm
+          curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
+          chmod +x kubectl
+          sudo mv kubectl /usr/local/bin/kubectl
+          kubectl version --client
+
+      # Step 3: Update the tag in Helm chart configuration files
+      - name: Update Helm Chart Docker Image Tags
+        run: |
+          echo "Updating Helm chart Docker image tags in the repository"
+          sed -i "s|image: prsm323/application:.*|image: prsm323/application:${{ env.IMAGE_TAG }}|g" helm-charts/deploy-as-code/charts/uba/backend/values.yaml
+          sed -i "s|image: prsm323/benefits:.*|image: prsm323/benefits:${{ env.IMAGE_TAG }}|g" helm-charts/deploy-as-code/charts/uba/backend/values.yaml
+          sed -i "s|image: prsm323/customer:.*|image: prsm323/customer:${{ env.IMAGE_TAG }}|g" helm-charts/deploy-as-code/charts/uba/backend/values.yaml
+
+      # Step 4: Deploy to EKS using Helm
+      - name: Deploy to EKS using Helm
+        run: |
+          helm upgrade --install uba-backend helm-charts/deploy-as-code/charts/uba/backend --namespace backend --set image.tag=${{ env.IMAGE_TAG }}
+          
+      # Step 5: Notify Success or Failure to Teams
+      - name: Send Success or Failure Message to Teams
+        run: |
+          TAG="${{ env.IMAGE_TAG }}"
+          SUCCESS_MESSAGE="EKS Deployment Successful: Service deployed with image tag $TAG."
+          FAILURE_MESSAGE="EKS Deployment Failed: Please check the Helm logs."
+
+          # Construct message
+          if [ $? -eq 0 ]; then
+            MESSAGE="$SUCCESS_MESSAGE"
+          else
+            MESSAGE="$FAILURE_MESSAGE"
+          fi
+
+          # Send message to Teams
+          curl -X POST -H 'Content-Type: application/json' \
+            -d "{\"text\":\"$MESSAGE\"}" ${{ secrets.TEAMS_WEBHOOK_URL }}
